Map<String, List<String>> wordlist = {
  "eldenring": [
    "Ancient Hero of Zamor",
    "Red Wolf of Radagon",
    "Elemer of the Briar",
    "Mimic Tear",
    "Bayle the Dread",
    "Demi-Human Queen Maggie",
    "Grafted Scion",
    "Mad Pumpkin Heads",
    "The Three Crystalians",
    "Rileigh the Idle",
    "Maliketh, the Black Blade",
    "Dragonkin Soldier",
    "Starscourge Radahn",
    "Dryleaf Dane",
    "Putrescent Knight",
    "Duelist Knight of the Great Jar",
    "Mohg, Lord of Blood",
    "Frenzied Duelist",
    "Demi-Human Chief",
    "Sanguine Noble",
    "Edgar The Revenger",
    "Nameless White Mask",
    "Scaly Misbegotten",
    "Jagged Peak Drake",
    "Rugalea the Great Red Bear",
    "Blackgaol Knight",
    "Maleigh Marais, Shaded Castle Castellan",
    "Godefroy the Grafted",
    "Anastasia, Tarnished-Eater",
    "Rakshasa",
    "Margit, the Fell Omen",
    "Ancient Dragon Senessax",
    "Old Knight Istvan",
    "Putrid Grave Warden Duelist",
    "Juno Hoslow, Knight of Blood",
    "Fallingstar Beast",
    "Glintstone Dragon Adula",
    "Chief Guardian Arghanthy",
    "Godskin Duo",
    "Godskin Noble",
    "Leda",
    "Royal Knight Loretta",
    "Fell Twin",
    "Salza, Fire Knight Sage",
    "Godskin Apostle",
    "Astel, Stars of Darkness",
    "Millicent",
    "Mad Pumpkin Head",
    "Battlemage Hugues",
    "Commander O'Neil",
    "Tree Sentinel Duo",
    "Moonrithyll, Carian Knight",
    "Fire Prelate",
    "Rellana, Twin Moon Knight",
    "Wormface",
    "Recusant Henricus",
    "Death Knight",
    "Ancestor Spirit",
    "Tree Sentinel",
    "Full-Grown Fallingstar Beast",
    "Night's Cavalry",
    "Thiollier",
    "Nox Monk",
    "Putrid Avatar",
    "Demi-Human Queen Margot",
    "Royal Revenant",
    "Misbegotten Warrior",
    "Cleanrot Knight",
    "Eleonora, Violet Bloody Finger",
    "Midra, Lord of the Frenzied Flame",
    "Magma Wyrm Makar",
    "Esgar, Priest of Blood",
    "Preceptor Miriam",
    "Fire Knight Queelign",
    "Deathbird",
    "Ancient Dragon Lansseax",
    "Glintstone Dragon Smarag",
    "Crucible Knight Ordovis",
    "Needle Knight Leda",
    "Margit, The Fell Omen",
    "Omenkiller",
    "Golden Hippopotamus",
    "Ralva the Great Red Bear",
    "Commander Niall",
    "Baleful Shadow",
    "Lamenter",
    "Recusant Bernahl",
    "Fire Giant",
    "Dragonkin Soldier of Nokstella",
    "Tanith's Crucible Knight",
    "Elden Beast",
    "Black Knight Garrew",
    "Commander Gaius",
    "Flying Dragon Agheel",
    "Red Bear",
    "Borealis the Freezing Fog",
    "Count Ymir, Mother of Fingers",
    "Festering Fingerprint Vyke",
    "Moore",
    "Misbegotten Crusader",
    "Regal Ancestor Spirit",
    "Crucible Knight Siluria",
    "Adan, Thief of Fire",
    "Red Wolf of the Champion",
    "Logur, the Beast Claw",
    "Draconic Tree Sentinel",
    "Bloodhound Knight Darriwil",
    "Erdtree Avatar",
    "Alexander Iron Fist",
    "Magnus the Beast Claw",
    "Guardian Golem",
    "Crucible Knight",
    "Miranda, the Blighted Bloom",
    "Scadutree Avatar",
    "Malenia, Blade of Miquella",
    "Vyke, Knight of the Roundtable",
    "Valiant Gargoyle Duo",
    "Bloodhound Knight",
    "Radagon of the Golden Order",
    "Tibia Mariner",
    "Elder Dragon Greyoll",
    "Messmer the Impaler",
    "Ancient Dragon-Man",
    "Crystalian",
    "Ulcerated Tree Spirit",
    "Demi-Human Swordmaster Onze",
    "Metyr, Mother of Fingers",
    "Fia’s Champions",
    "Dragonlord Placidusax",
    "Patches",
    "Necromancer Garris",
    "Erdtree Burial Watchdog Duo",
    "Moongrum, Carian Knight",
    "Inquisitor Ghiza",
    "Demi-Human Queen Marigga",
    "Spirit Caller Snail",
    "Bloody Finger Assassin",
    "Loretta, Knight of the Haligtree",
    "Leonine Misbegotten",
    "Black Blade Kindred",
    "Grave Warden Duelist",
    "Curseblade Labirith",
    "Bloody Finger Nerijus",
    "Bloody Finger Okina",
    "Demi-Human Queen Gilika",
    "Ensha of the Royal Remains",
    "Beastman of Farum Azula",
    "Great Horned Tragoth",
    "Runebear",
    "Swordhand of Night Anna",
    "Divine Beast Dancing Lion",
    "Spiritcaller Snail",
    "Lichdragon Fortissax",
    "Kindred Rot",
    "Sir Gideon Ofnir, the All-Knowing",
    "Rykard, Lord of Blasphemy",
    "Black Knight Edredd",
    "Mohg, the Omen",
    "Bols, Carian Knight",
    "Vargram, the Raging Wolf",
    "Flying Dragon Greyll",
    "Bell Bearing Hunter",
    "Erdtree Burial Watchdog",
    "Death Rite Bird",
    "Chief Bloodfiend",
    "Soldier of Godrick",
    "Hornsent",
    "Magma Wyrm",
    "Cemetery Shade",
    "Godfrey, First Elden Lord",
    "Dancer of Ranah",
    "Putrid Tree Spirit",
    "Mad Tongue Alberich",
    "Miranda the Blighted Bloom",
    "Astel, Naturalborn of the Void",
    "Nox Swordstress",
    "Stray Mimic Tear",
    "Alecto, Black Knife Ringleader",
    "Hoarah Loux, Warrior",
    "Decaying Ekzykes",
    "Great Wyrm Theodorix",
    "Ghostflame Dragon",
    "Madding Hand",
    "Morgott, the Omen King",
    "Jori, Elder Inquisitor",
    "Romina, Saint of the Bud",
    "Rennala, Queen of the Full Moon",
    "Beast Clergyman",
    "Abductor Virgins",
    "Black Knife Assassin",
    "Promised Consort Radahn",
    "Godrick the Grafted",
    "Onyx Lord",
    "Perfumer Tricia",
    "Stonedigger Troll",
    "Dung Eater",
  ],
  "maimai": [
    "星詠みとデスペラード",
    "分解収束テイル",
    "Spin me harder",
    "Backyun! －悪い女－",
    "とびだせ！TO THE COSMIC!!",
    "Lividi",
    "Round Round Spinning Around",
    "ミルキースター・シューティングスター",
    "華の集落、秋のお届け",
    "Geranium",
    "犬日和。",
    "Divide et impera!",
    "ナミダと流星",
    "躯樹の墓守",
    "一か罰",
    "Cosmic Train",
    "リフヴェイン",
    "星見草",
    "Secret Sleuth",
    "咲キ誇レ常世ノ華",
    "ねぇ、壊れタ人形ハ何処へ棄テらレるノ？",
    "Caliburne ～Story of the Legendary sword～",
    "VSpook!",
    "Mare Maris",
    "Shining Ray ～僕らの絆～",
    "Starry Colors",
    "Aetheric Energy",
    "Straight into the lights",
    "絡めトリック利己ライザー",
    "ジングルベル",
    "Komplexe",
    "ここからはじまるプロローグ。 (Kanon Remix)",
    "N3V3R G3T OV3R",
    "SPILL OVER COLORS",
    "maimaiちゃんのテーマ",
    "Fragrance",
    "Barbed Eye",
    "バーチャルダム　ネーション",
    "184億回のマルチトニック",
    "天国と地獄 -言ノ葉リンネ-",
    "Now or Never",
    "ここからはじまるプロローグ。",
    "Sweets×Sweets",
    "ステップアンドライム",
    "TEmPTaTiON",
    "Feel My Fire",
    "Selector",
    "おても☆Yan",
    "QZKago Requiem",
    "天火明命",
    "Limit Break",
    "炭★坑★節",
    "maiム・maiム feat.週刊少年マガジン",
    "Trick tear",
    "WiPE OUT MEMORIES",
    "Signature",
    "シックスプラン",
    "Color My World",
    "ARAIS",
    "LUCIA",
    "POWER OF UNITY",
    "チューリングの跡",
    "Swift Swing",
    "ネコ日和。",
    "ℝ∈Χ LUNATiCA",
    "Acceleration",
    "REAL VOICE",
    "End of Twilight",
    "タカハせ！名人マン",
    "時計の国のジェミニ",
    "True Love Song",
    "BaBan!! －甘い罠－",
    "Alcyone",
    "IF:U",
    "U&iVERSE -銀河鸞翔-",
    "Link",
    "NOIZY BOUNCE",
    "Kairos",
    "Lunatic Vibes",
    "ブレインジャックシンドローム",
    "オトヒメモリー☆ウタゲーション",
    "エスオーエス",
    "Neon Kingdom",
    "Believe the Rainbow",
    "Endless World",
    "トノサマビーム",
    "Kinda Way",
    "隠密あんみつDX",
    "でらっくmaimai♪てんてこまい!",
    "Mutation",
    "World's end loneliness",
    "Energizing Flame",
    "ホシシズク",
    "Pixel Voyage",
    "VeRForTe αRtE:VEiN",
    "Beat Opera op.1",
    "ピーマンたべたら",
    "渦状銀河のシンフォニエッタ",
    "四月の雨",
    "共鳴",
    "群青シグナル",
    "NAGAREBOSHI☆ROCKET",
    "BLACK ROSE",
    "JUMPIN' JUMPIN'",
    "悪戯",
    "モ°ルモ°ル (MZK Skippin' Remix)",
    "Blew Moon",
    "フタタビ",
    "遺伝子レベル∞スパイラル",
    "raputa",
    "Party☆People☆Princess",
    "BREaK! BREaK! BREaK!",
    "Oshama Scramble!",
    "STEREOSCAPE",
    "シエルブルーマルシェ",
    "VERTeX",
    "You Mean the World to Me",
    "Blows Up Everything",
    "DEVOTION",
    "トリアージ",
    "福宿音屋魂音泉",
    "Jumble Rumble",
    "フェイクフェイス・フェイルセイフ",
    "Ragnarok",
    "Dreampainter",
    "系ぎて",
    "Excalibur ～Revived resolution～",
    "にゃーにゃー冒険譚",
    "sølips",
    "KING is BACK!!",
    "Ether Second",
    "パラドクスイヴ",
    "Panopticon",
    "Dragoon",
    "アポカリプスに反逆の焔を焚べろ",
    "CITRUS MONSTER",
    "アージェントシンメトリー",
    "Starlight Disco",
    "スローアライズ",
    "高気圧ねこロック",
    "のじゃロリック",
    "Our Wrenally",
    "Night Fly",
    "Heavenly Blast",
    "Sage",
    "planet dancer",
    "7thSense",
    "Danza zandA",
    "いっしそう電☆舞舞神拳！",
    "FFT",
    "キリキリ舞Mine",
    "[X]",
    "Xenovcipher",
    "花と、雪と、ドラムンベース。",
    "AMABIE",
    "enchanted wanderer",
    "Glorious Crown",
    "Redemption",
    "Rising on the horizon",
    "Alea jacta est!",
    "Scarlet Wings",
    "Contrapasso -paradiso-",
    "Candy Tall Woman",
    "Nitrous Fury",
    "Beginning together!",
    "Metamorphosism",
    "地球",
    "Crazy Circle",
    "康莊大道",
    "TwisteD! XD",
    "デスパレイト",
    "オリフィス",
    "VANTABLACK RAVER",
    "L'épilogue",
    "ふらふらふら、",
    "Edelweiss",
    "Irresistible",
    "The Cursed Doll",
    "System “Z”",
    "CYCLES",
    "air's gravity",
    "プリズム△▽リズム",
    "KHYMΞXΛ",
    "MYTHOS",
    "OTOGEMA",
    "蒼穹舞楽",
    "サンバディ！",
    "ヱデン",
    "Streak",
    "ENJOY POLIS",
    "Heartbeats",
    "届かない花束",
    "BIRTH",
    "Yorugao",
    "\"411Ψ892\"",
    "デーモンベット",
    "ぼくたちいつでも　しゅわっしゅわ！",
    "ユメヒバナ",
    "Ultranova",
    "パラマウント☆ショータイム！！",
    "宵の鳥",
    "HERA",
    "ViRTUS",
    "My My My",
    "larva",
    "ヨミビトシラズ",
    "言ノ葉カルマ",
    "VIIIbit Explorer",
    "Axeria",
    "居並ぶ穀物と溜息まじりの運送屋",
    "Boys O’Clock",
    "Cider P@rty",
    "魔ジョ狩リ",
    "Tricolor⁂circuS",
    "STEEL TRANSONIC",
    "Last Samurai",
    "We Gonna Party",
    "Raven Emperor",
    "The Great Banquet",
    "りばーぶ",
    "Life Feels Good",
    "welcome to maimai!! with マイマイマー",
    "Technicians High",
    "火炎地獄",
    "Garakuta Doll Play",
    "Mystic Parade",
    "BREAK YOU!!",
    "≠彡\"/了→",
    "空威張りビヘイビア",
    "虹と太陽",
    "相思創愛",
    "#狂った民族２ PRAVARGYAZOOQA",
    "チエルカ／エソテリカ",
    "超常マイマイン",
    "GRÄNDIR",
    "星めぐり、果ての君へ。",
    "Lionheart",
    "記憶、記録",
    "GEMINI -M-",
    "ワンダーシャッフェンの法則",
    "Lia=Fail",
    "夢花火",
    "SILENT BLUE",
    "ユビキリ",
    "噛み係",
    "ツムギボシ",
    "Moon of Noon",
    "connecting with you",
    "ヤミツキ",
    "AMAZING MIGHTYYYY!!!!",
    "Horoscope Express",
    "ピリオドサイン",
    "GIGANTØMAKHIA",
    "Ututu",
    "Flashkick",
    "BETTER CHOICE",
    "FEEL the BEATS",
    "ほしぞらスペクタクル",
    "oboro",
    "HAGAKIRI",
    "言ノ葉遊戯",
    "みんなのマイマイマー",
    "封焔の135秒",
    "Revive The Rave",
    "Beat of getting entangled",
    "Prophesy One",
    "Hyper Active",
    "パラボラ",
    "UniTas",
    "HECATONCHEIR",
    "Justified",
    "Paradisoda",
    "前衛的Landscape",
    "P-qoq",
    "ぽわわん劇場",
    "mystique as iris",
    "オレンジの夏",
    "泣き虫O'clock",
    "パーフェクション",
    "Rainbow Rush Story",
    "モ°ルモ°ル",
    "Get Happy",
    "Never Give Up!",
    "Black Out",
    "生命不詳",
    "Aiolos",
    "BLACK SWAN",
    "ぴぴぱぷぅ！",
    "YKWTD",
    "白花の天使",
    "the EmpErroR",
    "Monochrome Rainbow",
    "RondeauX of RagnaroQ",
    "超熊猫的周遊記（ワンダーパンダートラベラー）",
    "マイオドレ！舞舞タイム",
    "Jörqer",
    "D✪N’T  ST✪P  R✪CKIN’",
    "分からない",
    "Falling",
    "Jouez Avec Moi?",
    "Nerverakes",
    "雷切-RAIKIRI-",
    "Bloody Trail",
    "Imitation:Loud Lounge",
    "シアトリカル・ケース",
    "Churros Parlor",
    "QuiQ",
    "RIFFRAIN",
    "Valsqotch",
    "♡マイマイマイラブ♡",
    "Turn around",
    "Magical Flavor",
    "FestivaLight",
    "アンビバレンス",
    "keep hopping",
    "Schwarzschild",
    "曖昧mind",
    "Cry Cry Cry",
    "MAXRAGE",
    "LANCE",
    "PANDORA PARADOXXX",
    "ぐるぐるWASH！コインランドリー・ディスコ",
    "MIRROR of MAGIC",
    "ガラテアの螺旋",
    "Sprintrances",
    "星空パーティーチューン",
    "RE:INCARNATED DRAGNER",
    "スリップフリップ",
    "ワードワードワード",
    "my flow",
    "Regulus",
    "Latent Kingdom",
    "FEEL ALIVE",
    "ソーラン☆節",
    "炎歌 -ほむらうた-",
    "アンバークロニクル",
    "勦滅",
    "洗脳",
    "Beautiful Future",
    "全世界共通リズム感テスト",
    "Stardust Memories",
    "Death Scythe",
    "ｉｓｏｐｈｏｔｅ",
    "Comet Panto Men!",
    "Strive against fate",
  ],
  'arcaea': [
    "Sayonara Hatsukoi",
    "Meta-Mysteria",
    "Hotarubi no Yuki",
    "Journey",
    "Gekka (Short Version)",
    "Hybris (The one who shattered)",
    "corps-sans-organes",
    "Dazzle hop",
    "Spirit of the Dauntless",
    "Dreamin' Attraction!!",
    "Galaxy Friends",
    "Corruption",
    "Malicious Mischance",
    "Equilibrium",
    "NEO WINGS",
    "Astral Quantization",
    "cyanine",
    "ENERGY SYNERGY MATRIX",
    "͟͝͞Ⅱ́̕",
    "Halcyon",
    "syūten",
    "Valhalla:0",
    "Seclusion",
    "XTREME",
    "Judgement",
    "Head BONK ache",
    "CYCLES",
    "Hikari",
    "Aurgelmir",
    "Brand new world",
    "Ai Drew",
    "Einherjar Joker",
    "Memory Forest",
    "Blue Rose",
    "Protoflicker",
    "Let's Rock (Arcaea mix)",
    "Sheriruth (Laur Remix)",
    "Pentiment",
    "Rugie",
    "Your voice so... feat. Such",
    "Old School Salvage",
    "Evening in Scarlet",
    "Nhelv",
    "To the Furthest Dream",
    "Ultimate taste",
    "Lights of Muse",
    "LastLast | MomentLast | Eternity",
    "Wish Upon a Snow",
    "1F√",
    "Jump",
    "ultradiaxon-N3",
    "Hypnotize",
    "On And On!! feat. Jenga",
    "Floating World",
    "Back to Basics",
    "Oracle",
    "Diode",
    "Relentless",
    "Dement ~after legend~",
    "Black MInD",
    "Last Celebration",
    "STAGER (ALL STAGE CLEAR)",
    "Ouvertüre",
    "Grimheart",
    "Romance Wars",
    "Lethal Voltage",
    "FURETE-MITAI",
    "False Embellishment",
    "Chromafill",
    "World Fragments III(radio edit)",
    "Ignition",
    "Be There",
    "Impure Bird",
    "Avant Raze",
    "astral.exe",
    "A Wandering Melody of Love",
    "Loveless Dress",
    "Innocence",
    "MIRINAE",
    "Dreadnought",
    "IgnotusIgnotus Afterburn",
    "Eccentric Tale",
    "Devillic Sphere",
    "WAIT FOR DAWN",
    "Genesis",
    "ω4",
    "Cybernecia Catharsis",
    "Paper Witch",
    "eden",
    "Final Step!",
    "Heart",
    "Sakura Fubuki",
    "Jingle",
    "April showers",
    "MORNINGLOOM",
    "#1f1e33",
    "Transient Space",
    "Masquerade Legion",
    "〇、",
    "The Formula",
    "Clotho and the stargazer",
    "Amekagura",
    "Libertas",
    "Cyaegha",
    "Stratoliner",
    "Macrocosmic Modulation",
    "Phantasia",
    "Antithese",
    "Distorted Fate",
    "HYPER VISION",
    "Teriqma",
    "La'qryma of the Wasteland",
    "MANTIS (Arcaea Ultra-Bloodrush VIP)",
    "Tie me down gently",
    "Garakuta Doll Play",
    "µ",
    "Vicious Heroism",
    "Vandalism",
    "Redolent Shape",
    "MAXRAGE",
    "Third Sun",
    "Give Me a Nightmare",
    "Red and Blue",
    "Altale",
    "Essence of Twilight",
    "Harutopia ~Utopia of Spring~",
    "Reinvent",
    "FANTA5Y",
    "Purple Verse",
    "SUPER AMBULANCE",
    "Kanbu de Tomatte Sugu Tokeru",
    "BLRINK",
    "ALTER EGO",
    "Rabbit In The Black Room",
    "To the Milky Way",
    "Aegleseeker",
    "Luna Rossa",
    "Sign of \"10.5km\"",
    "Crimson Quartz",
    "Lazy Addiction",
    "BADTEK",
    "INTERNET YAMERO",
    "Fallensquare",
    "Löschen",
    "Arcahv",
    "Lucifer",
    "Divine Light of Myriad",
    "Lethaeus",
    "trappola bewitching",
    "Red and Blue and Green",
    "Lightning Screw",
    "LunarOrbit -believe in the Espebranch road-",
    "The Message",
    "INTERNET OVERDOSE",
    "Bullet Waiting for Me (James Landino remix)",
    "world.execute(me);",
    "Heavenly caress",
    "Don't Fight The Music",
    "Maze No.9",
    "Viyella's Tears",
    "Sulfur",
    "Ignotus",
    "Medusa",
    "Alone & Lorn",
    "Qovat",
    "Tsuki ni Murakumo, Hana ni Kaze",
    "DRG",
    "AttraqtiA",
    "Blossoms",
    "Testify",
    "dropdead",
    "PRAGMATISM",
    "AI[UE]OON",
    "Fracture Ray",
    "Infinite Strife,",
    "Galactic Love",
    "LiftOff",
    "Spider's Thread",
    "Xeraphinite",
    "Felis",
    "Kissing Lucifer",
    "Remind the Souls (Short Version)",
    "γuarδina",
    "init()",
    "Tempestissimo",
    "GIMME DA BLOOD",
    "Leave All Behind",
    "New York Back Raise",
    "Flashback",
    "Nameless Passion",
    "Rays of Remnant",
    "Linear Accelerator",
    "carmine:scythe",
    "Defection",
    "memoryfactory.lzh",
    "Kanjou no Matenrou ～Arr.Demetori",
    "Designant.",
    "AMAZING MIGHTYYYY!!!!",
    "THE ULTIMACY",
    "overdead.",
    "MERLIN",
    "Overwhelm",
    "lastendconductor",
    "Used to be",
    "Rain of Conflict in a Radiant Abyss",
    "UNKNOWN LEVELS",
    "Strongholds",
    "GLORY：ROAD",
    "amygdata",
    "qualia -ideaesthesia-",
    "Vindication",
    "Misdeed -la bonté de Dieu et l'origine du mal-",
    "Ignotus Afterburn 2",
    "World Vanquisher",
    "next to you",
    "SUPERNOVA",
    "Singularity",
    "ouroboros -twin stroke of the end-",
    "Turbocharger",
    "nέo κósmo",
    "Party Vinyl",
    "Ikazuchi",
    "I've heard it said",
    "Ignotus Afterburn",
    "8-EM",
    "Swan Song",
    "Iconoclast",
    "Ävril -Flicka i krans-",
    "Hailstone",
    "Ashen 6oundary",
    "Raven's Pride",
    "PUPA",
    "ΟΔΥΣΣΕΙΑ",
    "Lost in the Abyss",
    "Abstruse Dilemma",
    "GIMMICK",
    "Bookmaker (2D Version)",
    "Ego Eimi",
    "Alice's Suitcase",
    "BlazinG AIR",
    "Bamboo",
    "FREEF4LL",
    "Renegade",
    "LAMIA",
    "B.B.K.K.B.K.K.",
    "Live Fast Die Young",
    "cocoro*cosmetic",
    "FLUFFY FLASH",
    "Astral tale",
    "Beautiful Dreamer",
    "ReviXy",
    "HIVEMIND",
    "Oblivia",
    "GOODTEK (Arcaea Edit)",
    "Awaken In Ruins",
    "Good bye, Merry-Go-Round.",
    "SOUNDWiTCH",
    "Magnolia",
    "cry of viyella",
    "Redraw the Colorless World",
    "Cosmo Pop Funclub",
    "Filament",
    "In Vain",
    "And Revive The Melody",
    "Anökumene",
    "BUCHiGiRE Berserker",
    "Arcana Eden",
    "Capella",
    "Hall of Mirrors",
    "KYOREN ROMANCE",
    "Silent Rush",
    "αterlβus",
    "To: Alice Liddell",
    "Purgatorium",
    "Sheriruth",
    "Crystal Gravity",
    "Free Myself",
    "Crimson Throne",
    "OMAKENO Stroke",
    "MAHOROBA",
    "LIVHT MY WΔY",
    "Call My Name feat. Yukacco",
    "with U",
    "NULL APOPHENIA",
    "Twilight Concerto",
    "Stasis",
    "Rise of the World",
    "Dies irae",
    "Technicolour",
    "Rise",
    "IONOSTREAM",
    "Alice à la mode",
    "Dot to Dot feat. shully",
    "[X]",
    "The Survivor (Game Edit)",
    "Got hive of Ra",
    "Arghena",
    "blue comet",
    "Empire of Winter",
    "HIVEMIND INTERLINKED",
    "Life is PIANO",
    "Nirv lucE",
    "san skia",
    "Aleph-0",
    "Black Territory",
    "Cosmica",
    "Kanagawa Cyber Culvert",
    "GENOCIDER",
    "0xe0e1ccull",
    "inkar-usi",
    "STARGATE EXTREME",
    "MVURBD",
    "Mistempered Malignance",
    "Désive",
    "Primeval Texture",
    "Moonheart",
    "Trap Crow",
    "Lost Emotion feat. nomico",
    "10pt8ion",
    "Antagonism",
    "Dandelion",
    "TEmPTaTiON",
    "Gensou no Satellite",
    "Inverted World",
    "Flyburg and Endroll",
    "99 Glooms",
    "Dantalion",
    "Lost Desire",
    "Senkyou",
    "AlterAle",
    "Dream goes on",
    "Small Cloud Sugar Candy",
    "Climax",
    "Faint Light (Arcaea Edit)",
    "Breach of Faith",
    "Evoltex (poppi'n mix)",
    "Illegal Paradise",
    "Particle Arts",
    "REKKA RESONANCE",
    "Logos",
    "Feels So Right feat. Renko",
    "One Last Drive",
    "Babaroque",
    "Infinity Heaven",
    "Fairytale",
    "Glow",
    "Suomi",
    "Mazy Metroplex",
    "SACRIFICE feat. ayame",
    "VECTOЯ",
    "Manic Jeer",
    "PRAGMATISMPRAGMATISM -RESURRECTION-",
    "G e n g a o z o",
    "Syro",
    "Prism",
    "Waltz for Lorelei",
    "Saint or Sinner",
    "Vulcānus",
    "Heavensdoor",
    "Dynitikós",
    "Let you DIVE! (nitro rmx)",
    "felys final remix",
    "Coastal Highway",
    "Alexandrite",
    "enchanted love",
    "Vivid Theory",
    "CROSS†OVER",
    "shrink",
    "World Ender",
    "SingularitySingularity VVVIP",
    "Xanatos",
    "Modelista",
    "Far Away Light",
    "Beside You",
    "Lumia",
    "Hiiro Gekka, Kyoushou no Zetsu (nayuta 2017 ver.)",
    "Chronostasis",
    "Singularity VVVIP",
    "Black Lotus",
    "Scarlet Cage",
    "Moonlight of Sand Castle",
    "Quon",
    "conflict",
    "Dialnote",
    "Trrricksters!!",
    "DDD",
    "Tutorial",
    "Chelsea",
    "Lament Rain",
    "Hidden Rainbows of Epicurus",
    "Yosakura Fubuki",
    "First Snow",
    "CROSS†SOUL",
    "Blocked Library",
    "Distortion Human",
    "Oshama Scramble!",
    "IMPACT",
    "epitaxy",
    "Haze of Autumn",
    "Lapis",
    "REconstruction",
    "Snow White",
    "Specta",
    "Lost Civilization",
    "Auxesia",
    "7thSense",
    "SAIKYO STRONGER",
    "goldenslaughterer",
    "Can I Friend You on Bassbook? Lol",
    "Prayer",
    "Tiferet",
    "Summer Fireworks of Love",
    "TeraVolt",
    "NULCTRL",
    "Scarlet Lance",
    "Axium Crisis",
    "Surrender",
    "Monochrome Princess",
    "Mirzam",
    "Callima Karma",
    "CHAOS",
    "Dual Doom Deathmatch",
    "DX Choseinou Full Metal Shojo",
    "Metallic Punisher",
    "Red and BlueRed and Blue and Green",
    "HELLOHELL",
    "Altair (feat. *spiLa*)",
    "PICO-Pico-Translation!",
    "Solitary Dream",
    "Shades of Light in a Transcendent Realm",
    "Heart Jackin'",
    "Lucid Traveler",
    "Ascent",
    "Grievous Lady",
    "Ringed Genesis",
    "BATTLE NO.1",
    "Astra walkthrough",
    "PRIMITIVE LIGHTS",
    "Vexaria",
    "Lawless Point",
    "Blaster",
    "Dancin' on a Cat's Paw",
    "Ether Strike",
    "Vicious HeroismVicious [ANTi] Heroism",
    "IZANA",
    "RGB",
    "DataErr0r",
    "Paradise",
    "DA'AT -The First Seeker of Souls-",
    "dropdeadoverdead.",
    "Chronicle",
  ],
};
